<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Vishals-MacBook-Air.local" failures="1" tests="1" name="FirefoxTest" time="14.704" errors="0" timestamp="2024-09-06T22:34:13 IST">
  <testcase classname="com.OpenCart.Register.TC_RegisterPage" name="RegisterPage" time="1.47">
    <failure type="java.lang.AssertionError" message="Test case failed due to an exception.">
      <![CDATA[java.lang.AssertionError: Test case failed due to an exception.
at com.OpenCart.Register.TC_RegisterPage.RegisterPage(TC_RegisterPage.java:79)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- RegisterPage -->
</testsuite> <!-- FirefoxTest -->
